In [70]:
import tensorflow as tf #we import tensorflow as tf

In [71]:
import keras

In [72]:
#importing important libraries for data analysis
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [73]:
dataset=pd.read_csv("Churn_Modelling.csv")#to read the dataset which is present in Churn_Modelling.csv

In [74]:
dataset.head()
#it is a dataset from a bank(6 months) which shows that there are some customers who are going to leave the bank or not and some data also given realed to the customers. Our task is to train our ANN model on the given dataset and on the basis of that data we con find whether that particular customer going to leave the bank or not.

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [75]:
x=dataset.iloc[:,3:13].values#there are only column number 3 to 12 because that values are only responsible for the output.
y=dataset.iloc[:,13].values#output



In [76]:
x#shows an array with contain value of all rows from column 3 to 12.

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [77]:
y#1 represents customer is with bank, 0 reprents that customer  leaves the bank.

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [78]:
#encoding categorical data
#our model is not able to understand alphabets like france, male,female etc so we are going to convert it into 0,1,2,...etc
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x=LabelEncoder()
x[:,1]=labelencoder_x.fit_transform(x[:,1])#convert france into 0,Germany into 1 and Spain into 3 and so on 
x[:,2]=labelencoder_x.fit_transform(x[:,2])#convert female into 0 and male into 1

In [79]:
x.shape

(10000, 10)

In [80]:
x[1]

array([608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58], dtype=object)

In [81]:
onehotencoder=OneHotEncoder(categorical_features=[1])#check out this link to understand onehot encoder "https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/" her column number expand into 3 columns that is why now total number of columns is 12
x1=onehotencoder.fit_transform(x).toarray()

In [82]:
print(x.shape)
print(x[1])

(10000, 10)
[608 2 0 41 1 83807.86 1 0 1 112542.58]


In [84]:
x.shape

(10000, 10)

In [85]:
from sklearn.model_selection import train_test_split#we import this to divide our data into training data and testing data

In [86]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)#80% of total data is only used for training and rest 20% is for testing.

In [87]:
from sklearn.preprocessing import StandardScaler

In [88]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

E:\New folder\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


# ANN Starts

In [89]:
from keras.models import Sequential#use for intialising
from keras.layers import Dense#use for makinf hidden layers

In [90]:
#intialising ANN
classifier=Sequential()#we intialise our model
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=10))#first hidden layer take 10 input gives 6 output and works on rectifier function.

E:\New folder\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=10, units=6, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [91]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))#2nd input layer

E:\New folder\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [92]:
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))#output layer

E:\New folder\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [93]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#during compilation use optimiser adam(stochastic gradient descent)

In [94]:
classifier.fit(x_train,y_train,batch_size=10,nb_epoch=200)

E:\New folder\lib\site-packages\keras\models.py:944: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/200
8000/8000 [==============================] - 3s 390us/step - loss: 0.4945 - acc: 0.7934
Epoch 2/200
8000/8000 [==============================] - 1s 125us/step - loss: 0.4340 - acc: 0.7936
Epoch 3/200
8000/8000 [==============================] - 1s 123us/step - loss: 0.4281 - acc: 0.7936
Epoch 4/200
8000/8000 [==============================] - 1s 130us/step - loss: 0.4237 - acc: 0.8134
Epoch 5/200
8000/8000 [==============================] - 1s 132us/step - loss: 0.4209 - acc: 0.8264
Epoch 6/200
8000/8000 [==============================] - 1s 127us/step - loss: 0.4189 - acc: 0.8299
Epoch 7/200
8000/8000 [==============================] - 1s 146us/step - loss: 0.4173 - acc: 0.8302
Epoch 8/200
8000/8000 [==============================] - 1s 129us/step - loss: 0.4160 - acc: 0.8332
Epoch 9/200
8000/8000 [==============================] - 1s 124us/step - loss: 0.4146 - acc: 0.8332
Epoch 10/200
8000/8000 [==============================] - 1s 128us/step - loss: 0.4139 - acc: 0.8341

8000/8000 [==============================] - 1s 119us/step - loss: 0.3933 - acc: 0.8390
Epoch 83/200
8000/8000 [==============================] - 1s 133us/step - loss: 0.3929 - acc: 0.8402
Epoch 84/200
8000/8000 [==============================] - 1s 120us/step - loss: 0.3934 - acc: 0.8400
Epoch 85/200
8000/8000 [==============================] - 1s 123us/step - loss: 0.3926 - acc: 0.8382
Epoch 86/200
8000/8000 [==============================] - 1s 146us/step - loss: 0.3935 - acc: 0.8402
Epoch 87/200
8000/8000 [==============================] - 1s 125us/step - loss: 0.3931 - acc: 0.8389
Epoch 88/200
8000/8000 [==============================] - 1s 125us/step - loss: 0.3935 - acc: 0.8389
Epoch 89/200
8000/8000 [==============================] - 1s 126us/step - loss: 0.3935 - acc: 0.8404
Epoch 90/200
8000/8000 [==============================] - 1s 126us/step - loss: 0.3936 - acc: 0.8391
Epoch 91/200
8000/8000 [==============================] - 1s 128us/step - loss: 0.3929 - acc: 0.8390
Epo

8000/8000 [==============================] - 1s 123us/step - loss: 0.3883 - acc: 0.8410
Epoch 163/200
8000/8000 [==============================] - 1s 124us/step - loss: 0.3886 - acc: 0.8385
Epoch 164/200
8000/8000 [==============================] - 1s 121us/step - loss: 0.3881 - acc: 0.8382
Epoch 165/200
8000/8000 [==============================] - 1s 122us/step - loss: 0.3873 - acc: 0.8405
Epoch 166/200
8000/8000 [==============================] - 1s 122us/step - loss: 0.3874 - acc: 0.8401
Epoch 167/200
8000/8000 [==============================] - 1s 123us/step - loss: 0.3872 - acc: 0.8405
Epoch 168/200
8000/8000 [==============================] - 1s 125us/step - loss: 0.3862 - acc: 0.8417
Epoch 169/200
8000/8000 [==============================] - 1s 124us/step - loss: 0.3857 - acc: 0.8416
Epoch 170/200
8000/8000 [==============================] - 1s 123us/step - loss: 0.3859 - acc: 0.8401
Epoch 171/200
8000/8000 [==============================] - 1s 125us/step - loss: 0.3852 - acc: 0

In [95]:
y_pred=classifier.predict(x_test)
y_pred=(y_pred>0.5)

In [96]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [97]:
cm

array([[1544,   70],
       [ 216,  170]], dtype=int64)